<div class="main">
	<form class="form-2">
		<h1><span class="log-in">Log in</span> | <span class="sign-up">Autentificacion</span></h1>
		<p class="float">
			<label for="login"><i class="icon-user"></i>Username</label>
			<input type="text" name="login" placeholder="Usuario">
		</p>
		<p class="float">
			<label for="password"><i class="icon-lock"></i>Password</label>
			<input type="password" name="password" placeholder="Clave" class="showpassword">
		</p>
		<p class="clearfix">
			<a href="#" class="log-twitter"></a>
			<input type="submit" name="submit" value="Log in | Entrar">
		</p>
	</form>
</div>