<div id="page_error_ico">
	<img alt="Page 404" src="/img/iconos/404.png">
</div>
<div id="page_error_info">
	<h1>Error</h1>
	<h2>404 - Recurso no encontrado | Resource not found</h2>
	<h3><?php echo "http://" . $_SERVER['HTTP_HOST'] . ":" . $_SERVER['SERVER_PORT'] . $_SERVER['REQUEST_URI']; ?></h3>
	<p>Lamentamos informarle que el recurso solicitado no existe o no se encuentra disponible por el momento. Lo invimos a revisar la direccion ingresada o contactar al equipo de soporte tecnico para reportar el inconveniente.</p>
	<p>	
		Sorry, the requested resource does not exist or is not available at the moment. What invimos to check directions or to contact technical support team to report the problem.
	</p>	
		
</div>