<div id="page_error_ico">
	<img alt="Page 404" src="/img/iconos/system_error.png">
</div>
<div id="page_error_info">
	<h1>Error</h1>
	<h2>500 - Error interno del servidor | Internal server error</h2>
	<h3><?php echo "http://" . $_SERVER['HTTP_HOST'] . ":" . $_SERVER['SERVER_PORT'] . $_SERVER['REQUEST_URI']; ?></h3>
	<p>El servidor no ha podido enviar el recurso solicitado debido a un error interno. Por favor contactar a su soporte tecnico para reportar el inconveniente.</p>
	<p>The server was unable to send the requested resource, has generated an internal error.Please contact your technical support to report the problem.</p>		
</div>