<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title><?php
		if (isset($this -> title)) {
			echo "Framework - " . $this -> title;
		} else {
			echo "Framework";
		}
			?></title>
		<!-- Jquery -->
		<link rel="stylesheet" type="text/css" media="screen" href="/jquery/css/default/jquery-ui-1.10.1.custom.min.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="/css/login.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="/css/font-awesome.css" />
		
		<script src="/jquery/js/jquery-1.9.1.js"></script>
		<script src="/jquery/js/jquery-ui-1.10.1.custom.js"></script>
	</head>
	<body>
    	<?php $this -> getView(); ?>
	</body>
</html>